### PR TITLE
Adjust Types for Typescript & Allow Headless Mode

### PR DESCRIPTION
**Pull request by MuckT**
@mfrachet was having some issues with getting cypress-audit to run in headless mode I made the fixes attached in this pull request; With the setup described in #58 and these changes I am able to run cypress-audit on headless chrome browser and receive accurate results.

Summary of changes:
- Create 'types' folder
- Move index.d.ts to that folder
- Add reference to cypress in the top line of the index.d.ts
- misc linting

### CODE REVIEW

**Comment by mfrachet** [comment]
First of all, thank you so much for this pull request 🙏🏻 

Then, I don't have that much knowledge on creating d.ts files. Could you explain me how moving the declaration file inside a types folder solve the issue?

**Comment by MuckT** [comment]
I had [cypress-file-upload](https://github.com/abramenal/cypress-file-upload) running for a few tests sook a look at their [index.d.ts](https://github.com/abramenal/cypress-file-upload/tree/master/types).

**Comment by MuckT** [comment]
@mfrachet any updates on this PR; Is there something needed from me to get this merged in?

**Comment by MuckT** [comment]
> First of all, thank you so much for this pull request 🙏🏻
> 
> Then, I don't have that much knowledge on creating d.ts files. Could you explain me how moving the declaration file inside a types folder solve the issue?

I think the type declaration at the top of the index.d.ts is main thing fix; I'll test that and adjust the PR if that's the case.
```typescript
/// <reference types="cypress" />
```

**Comment by mfrachet** [comment]
Thanks for your help here. I'm having hard time, switched job etc.. I'm not as active as I would like to be these days 😅

**Comment by mfrachet** [comment]
I will merge in the actual situation, release a fix and iterate from that point. This is opened for a long time and you did great with that, thank you 🙏🏻

**Pull request merged**
