### PR TITLE
fix: lighthouse .cjs import and use legacy navigation

### PR DESCRIPTION
**Pull request by MuckT**
### Description

A follow up PR to fix #209 to use the `.cjs` import.

Fixes: #207

### CODE REVIEW

**Comment by MuckT** [comment]
@mfrachet when I update the import of lightHouseLib to `.cjs` in the `examples/cra-authenticated/node_modules/@cypress-audit/lighthouse/src/task.js` the tests are passing locally.

**Comment by MuckT** [comment]
@mfrachet is there a way the tests can use the local version of `cypress-audit` instead of the latest version on npm?

**Comment by mfrachet** [comment]
`npm run bootstrap` should do the trick with lerna and its workspaces (at the root of the project)

**Comment by mfrachet** [comment]
It has not worked with the workspaces?

Can you try the following pleas (using module imports) at the root:

- `rm -rf ./**/node_modules`
- `npm install`
- `npm run bootstrap`

and tell me if the workspace module resolution is working?

**Comment by MuckT** [comment]
@mfrachet I think I am getting the version 1.4.0 of cypress-audit in the tests if run the above commands run then run the tests locally.

```
Error [ERR_REQUIRE_ESM]: require() of ES Module /repos/cypress-audit/examples/cra-authenticated/node_modules/lighthouse/core/index.js from /repos/cypress-audit/examples/cra-authenticated/node_modules/@cypress-audit/lighthouse/src/task.js not supported.
Instead change the require of index.js in /repos/cypress-audit/examples/cra-authenticated/node_modules/@cypress-audit/lighthouse/src/task.js
```

**Comment by mfrachet** [comment]
Arg, you're PR works for me locally using the lerna bootstrap command, something weird is happening

**Comment by MuckT** [comment]
I'll revert those change.

**Comment by mfrachet** [comment]
I just moved to pnpm + lerna in https://github.com/mfrachet/cypress-audit/pull/214 and cherry picked your changes regarding the commonjs fix. Let's cross the fingers that people using ESM will not inc too soon :p

Thanks for your help and patience on this one 🙏🏻 . I will merge the pnpm thing and iterate from there

**Pull request closed without merging**
